openapi: 3.1.0
info:
  title: Booking API
  description: API to book a rental car or retrieve a booking's details
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /booking/confirm:
    post:
      tags:
        - booking-controller
      operationId: confirmBooking
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BookingRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
                format: uuid
  /booking/{id}:
    get:
      tags:
        - booking-controller
      operationId: retrieveBookingDetails
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/BookingDetailsResponse"
components:
  schemas:
    BookingRequest:
      type: object
      properties:
        drivingLicenseNumber:
          type: string
          minLength: 1
        customerAge:
          type: integer
          format: int32
          minimum: 18
        reservationStart:
          type: string
          format: date
        reservationEnd:
          type: string
          format: date
        carSegment:
          type: string
          enum:
            - SMALL
            - MEDIUM
            - LARGE
            - EXTRA_LARGE
      required:
        - carSegment
        - customerAge
        - drivingLicenseNumber
        - reservationEnd
        - reservationStart
    BookingDetailsResponse:
      type: object
      properties:
        drivingLicenseNumber:
          type: string
          minLength: 1
        customerName:
          type: string
          minLength: 1
        customerAge:
          type: integer
          format: int32
          minimum: 18
        reservationStart:
          type: string
          format: date
        reservationEnd:
          type: string
          format: date
        carSegment:
          type: string
          enum:
            - SMALL
            - MEDIUM
            - LARGE
            - EXTRA_LARGE
        rentalPrice:
          type: number
      required:
        - carSegment
        - customerAge
        - customerName
        - drivingLicenseNumber
        - reservationEnd
        - reservationStart
